#!/bin/bash
# Copy the real Scene.swift in, then run the suite.
#
# Copied rather than symlinked because the repo is edited on Windows and
# synced by git, where symlinks are unreliable. Copied VERBATIM - the
# tests use @testable import, which sees internal symbols, so the app
# source needs no `public` sprinkled through it for this to work.
set -euo pipefail
cd "$(dirname "$0")"
SRC=../binge/Models/Scene.swift
test -f "$SRC" || { echo "missing $SRC" >&2; exit 1; }
# git does not track empty directories, and the copied source is
# gitignored, so this does not exist on a fresh clone.
mkdir -p Sources/SceneLogic
{
  echo "// GENERATED by run.sh from binge/Models/Scene.swift - do not edit."
  cat "$SRC"
} > Sources/SceneLogic/Scene.swift
swift test "$@"
